import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./_contexts/CartContext";
import { Header } from "./_components/layout/Header";
import { Footer } from "./_components/layout/Footer";
import { CartDrawer } from "./_components/layout/CartDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const proximaNova = localFont({
  variable: "--font-proxima-nova",
  src: [
    {
      path: "../public/fonts/Proxima Nova Regular.ttf",
      weight: "400",
      style: "normal",
      display: "swap",
    },
    {
      path: "../public/fonts/Proxima Nova Semibold.ttf",
      weight: "700",
      style: "normal",
      display: "swap",
    },
    {
      path: "../public/fonts/Proxima Nova Light.ttf",
      weight: "300",
      style: "normal",
      display: "swap",
    },
  ],
});

export const metadata = {
  title: "Samosa",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${proximaNova.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <div className="min-h-screen flex flex-col">
            <Header />
            <main className="flex-1">{children}</main>
            <Footer />
            <CartDrawer />
          </div>
        </CartProvider>
      </body>
    </html>
  );
}
