import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { CartProvider } from "./_contexts/CartContext";
import { Header } from "./_components/layout/Header";
import { Footer } from "./_components/layout/Footer";
import { CartDrawer } from "./_components/layout/CartDrawer";
import Providers from "./_components/Providers";
import { getProduct } from "./_lib/shopify";
import ProductProvider from "./_components/ProductProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const proximaNova = localFont({
  variable: "--font-proxima-nova",
  src: [
    {
      path: "../public/fonts/Proxima Nova Regular.ttf",
      weight: "400",
      style: "normal",
      display: "swap",
    },
    {
      path: "../public/fonts/Proxima Nova Semibold.ttf",
      weight: "700",
      style: "normal",
      display: "swap",
    },
    {
      path: "../public/fonts/Proxima Nova Light.ttf",
      weight: "300",
      style: "normal",
      display: "swap",
    },
  ],
});

export const metadata = {
  title: "Samosa",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const product = await getProduct("samosa", "GB");
  // console.log(product);

  return (
    <html lang="en" className={`${proximaNova.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Providers country="GB">
          <ProductProvider product={product}>
            <div className="min-h-screen flex flex-col">
              <Header />
              <main className="flex-1">{children}</main>
              <Footer />
              <CartDrawer />
            </div>
          </ProductProvider>
        </Providers>
      </body>
    </html>
  );
}
